/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTeamRouteImport } from './routes/_app.team'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppLeadsRouteImport } from './routes/_app.leads'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAgentDashboardRouteImport } from './routes/_app.agent-dashboard'
import { Route as AppAdminDashboardRouteImport } from './routes/_app.admin-dashboard'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsRoute = AppLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentDashboardRoute = AppAgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-dashboard': typeof AppAdminDashboardRoute
  '/agent-dashboard': typeof AppAgentDashboardRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin-dashboard': typeof AppAdminDashboardRoute
  '/agent-dashboard': typeof AppAgentDashboardRoute
  '/dashboard': typeof AppDashboardRoute
  '/leads': typeof AppLeadsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin-dashboard': typeof AppAdminDashboardRoute
  '/_app/agent-dashboard': typeof AppAgentDashboardRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/leads': typeof AppLeadsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin-dashboard'
    | '/agent-dashboard'
    | '/dashboard'
    | '/leads'
    | '/settings'
    | '/team'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin-dashboard'
    | '/agent-dashboard'
    | '/dashboard'
    | '/leads'
    | '/settings'
    | '/team'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/admin-dashboard'
    | '/_app/agent-dashboard'
    | '/_app/dashboard'
    | '/_app/leads'
    | '/_app/settings'
    | '/_app/team'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads': {
      id: '/_app/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AppLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent-dashboard': {
      id: '/_app/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AppAgentDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin-dashboard': {
      id: '/_app/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAgentDashboardRoute: typeof AppAgentDashboardRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppLeadsRoute: typeof AppLeadsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAgentDashboardRoute: AppAgentDashboardRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppLeadsRoute: AppLeadsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
